const CATEGORIES_GET = "CATEGORIES_GET";
const CATEGORY_ADD = 'CATEGORY_ADD';
const CATEGORY_DELETE = "CATEGORY_DELETE"
const CATEGORY_EDIT = "CATEGORY_EDIT"
const CATEGORIES_SORT ="CATEGORIES_SORT"

const types = {
    CATEGORIES_GET,
    CATEGORY_ADD,
    CATEGORY_DELETE,
    CATEGORY_EDIT,
    CATEGORIES_SORT
};

export default types;
