const EXCHANGES_GET = "EXCHANGES_GET";
const EXCHANGE_ADD = 'EXCHANGE_ADD';
const EXCHANGE_DELETE = "EXCHANGE_DELETE"
const EXCHANGE_EDIT = "EXCHANGE_EDIT"
const EXCHANGES_SORT ="EXCHANGES_SORT"

const types = {
    EXCHANGES_GET,
    EXCHANGE_ADD,
    EXCHANGE_DELETE,
    EXCHANGE_EDIT,
    EXCHANGES_SORT
};

export default types;
